language: c

env: KPM_restore_options=" -s https://www.myget.org/F/aspnetvnext/api/v2 -s https://nuget.org/api/v2/"

install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - echo "deb http://us.archive.ubuntu.com/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/trusty.list
  - sudo apt-get update
  - sudo apt-get install mono-devel
  - wget https://github.com/sass/libsass/archive/3.0.2.tar.gz -O libsass-3.0.2.tar.gz
  - tar xvf libsass-3.0.2.tar.gz
  - pushd libsass-3.0.2
  - autoreconf -fvi
  - ./configure
  - make && sudo make install
  - sudo ldconfig
  - popd
  - mozroots --import --sync

script:
  - mono --version
  - ./build.sh
